package com.sdm3.parent.core.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class ProductSchoolColors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val onSurfaceMuted: Color,
    val onSurfaceFaint: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineSubtle: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val inversePrimary: Color,
    val scrim: Color,
    val surfaceGlass: Color,
    val glassOutline: Color,
    val navigationActive: Color,
    val success: Color,
    val warning: Color,
    val danger: Color,
    val info: Color,
    val disabled: Color,
    val liquidGlassSurface: Color = Color.Unspecified,
    val liquidGlassBorder: Color = Color.Unspecified,
    val liquidGlassHighlight: Color = Color.Unspecified,
    val liquidGlassShadow: Color = Color.Unspecified,
    val successContainer: Color = Color.Unspecified,
    val warningContainer: Color = Color.Unspecified,
    val dangerContainer: Color = Color.Unspecified,
    val infoContainer: Color = Color.Unspecified,
)

fun productSchoolLightColors() = ProductSchoolColors(
    primary = Color(0xFF001B3D),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD6E3FF),
    onPrimaryContainer = Color(0xFF001B3D),
    secondary = Color(0xFFD4AF37),
    onSecondary = Color(0xFF1A1300),
    secondaryContainer = Color(0xFFFED65B),
    onSecondaryContainer = Color(0xFF745C00),
    tertiary = Color(0xFF2D6CDF),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD6E3FF),
    onTertiaryContainer = Color(0xFF001B3D),
    error = Color(0xFFC13A3A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF7F8FA),
    onBackground = Color(0xFF0F1722),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF0F1722),
    onSurfaceMuted = Color(0xFF525B66),
    onSurfaceFaint = Color(0xFF8B93A0),
    surfaceVariant = Color(0xFFDBE4ED),
    onSurfaceVariant = Color(0xFF44474E),
    outline = Color(0xFFE2E6EB),
    outlineSubtle = Color(0xFFEFF1F4),
    inverseSurface = Color(0xFF0F1722),
    inverseOnSurface = Color(0xFFF7F8FA),
    inversePrimary = Color(0xFFD6AF37),
    scrim = Color(0xFF000000).copy(alpha = 0.32f),
    surfaceGlass = Color(0x8CFFFFFF),
    glassOutline = Color(0x33FFFFFF),
    navigationActive = Color(0xFFD4AF37),
    success = Color(0xFF1E8E5A),
    warning = Color(0xFFC98A1D),
    danger = Color(0xFFC13A3A),
    info = Color(0xFF2D6CDF),
    disabled = Color(0xFFC4C6CF),
    liquidGlassSurface = Color(0xD9FFFFFF),      // alpha 0.85
    liquidGlassBorder = Color(0x4DFFFFFF),       // alpha 0.30
    liquidGlassHighlight = Color(0x59FFFFFF),    // alpha 0.35
    liquidGlassShadow = Color(0x14000000),       // alpha 0.08
    successContainer = Color(0x1A1E8E5A),        // alpha 0.10
    warningContainer = Color(0x1AC98A1D),        // alpha 0.10
    dangerContainer = Color(0x1AC13A3A),         // alpha 0.10
    infoContainer = Color(0x1A2D6CDF),           // alpha 0.10
)

fun productSchoolDarkColors() = ProductSchoolColors(
    primary = Color(0xFF9CCAFF),
    onPrimary = Color(0xFF001B3D),
    primaryContainer = Color(0xFF00315C),
    onPrimaryContainer = Color(0xFFD6E3FF),
    secondary = Color(0xFFE5C158),
    onSecondary = Color(0xFF1A1300),
    secondaryContainer = Color(0xFF574400),
    onSecondaryContainer = Color(0xFFFFE082),
    tertiary = Color(0xFF82B1FF),
    onTertiary = Color(0xFF002244),
    tertiaryContainer = Color(0xFF003F80),
    onTertiaryContainer = Color(0xFFD6E3FF),
    error = Color(0xFFFF8A80),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF000B18),
    onBackground = Color(0xFFF1F5F9),
    surface = Color(0xFF001530),
    onSurface = Color(0xFFF1F5F9),
    onSurfaceMuted = Color(0xFF94A9C4),
    onSurfaceFaint = Color(0xFF647B9B),
    surfaceVariant = Color(0xFF0D2547),
    onSurfaceVariant = Color(0xFFCBDDF5),
    outline = Color(0xFF334A6B),
    outlineSubtle = Color(0xFF1A3152),
    inverseSurface = Color(0xFFF1F5F9),
    inverseOnSurface = Color(0xFF000B18),
    inversePrimary = Color(0xFF001B3D),
    scrim = Color(0xFF000000).copy(alpha = 0.65f),
    surfaceGlass = Color(0xCC001530),
    glassOutline = Color(0x1AFFFFFF),
    navigationActive = Color(0xFFE5C158),
    success = Color(0xFF4ADE80),
    warning = Color(0xFFFBBF24),
    danger = Color(0xFFF87171),
    info = Color(0xFF60A5FA),
    disabled = Color(0xFF334A6B),
    liquidGlassSurface = Color(0xD9001530),      // alpha 0.85
    liquidGlassBorder = Color(0x26FFFFFF),       // alpha 0.15
    liquidGlassHighlight = Color(0x1AFFFFFF),    // alpha 0.10
    liquidGlassShadow = Color(0x33000000),       // alpha 0.20
    successContainer = Color(0x264ADE80),        // alpha 0.15
    warningContainer = Color(0x26FBBF24),        // alpha 0.15
    dangerContainer = Color(0x26F87171),         // alpha 0.15
    infoContainer = Color(0x2660A5FA),           // alpha 0.15
)

fun ProductSchoolColors.toMaterialColorScheme(darkTheme: Boolean) =
    if (darkTheme) toDarkMaterialColorScheme() else toLightMaterialColorScheme()

private fun ProductSchoolColors.toLightMaterialColorScheme() = androidx.compose.material3.lightColorScheme(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryContainer = secondaryContainer,
    onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary,
    onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer,
    onTertiaryContainer = onTertiaryContainer,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    outline = outline,
    inverseSurface = inverseSurface,
    inverseOnSurface = inverseOnSurface,
    inversePrimary = inversePrimary,
    scrim = scrim,
)

private fun ProductSchoolColors.toDarkMaterialColorScheme() = androidx.compose.material3.darkColorScheme(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryContainer = secondaryContainer,
    onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary,
    onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer,
    onTertiaryContainer = onTertiaryContainer,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    outline = outline,
    inverseSurface = inverseSurface,
    inverseOnSurface = inverseOnSurface,
    inversePrimary = inversePrimary,
    scrim = scrim,
)
